# Generated by Django 3.0.8 on 2020-07-29 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecciones',
            fields=[
                ('idLeccion', models.AutoField(primary_key=True, serialize=False)),
                ('NombreLeccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('idPregunta', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=300)),
                ('puntos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=300)),
                ('RespuestaCorrecta', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioRoll',
            fields=[
                ('idAlumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('rol', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('idCurso', models.AutoField(primary_key=True, serialize=False)),
                ('NombreCurso', models.CharField(max_length=100)),
                ('Descripcion', models.CharField(max_length=150)),
                ('lecciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Lecciones')),
            ],
        ),
    ]
